config/routes.rb
Rails.application.routes.draw do
    
    resources :events

    root "users#home"
    get "/users" => "users#index", as: :users
    post "/users" => "users#create", as: :create_user
    get "/users/new" => "users#new", as: :new_user
    get "/users/map" => "users#map", as: :user_map
    get "/users/about" => "users#about", as: :about_footy
    get "/users/home" => "users#home"
    get "/users/welcome" => "users#welcome"
    get "/users/:id" => "users#show", as: :user_profile
    get "/users/:id/edit" => "users#edit", as: :edit_users
    put "/users/:id" => "posts#update", as: :update_user
    patch "/users/:id" =>"users#update"
    delete "/users/:id" => "users#destroy"


    get "/sessions/new" => "sessions#new", as: :new_session
    post "/sessions" => "sessions#create", as: :create_session
    get "/sessions/destroy" => "sessions#destroy", as: :destroy_session

    get "/posts" => "posts#index", as: :posts
    get "/posts/new" => "posts#new", as: :new_post
    post "/posts" => "posts#create", as: :create_post
    get "/posts/:id" => "posts#show", as: :post
    get "/posts/:id/edit" => "posts#edit", as: :edit_post
    put "/posts/:id" => "posts#update"
    patch "/posts/:id" => "posts#update"
    delete "posts/:id" => "posts#destroy"

    post "/posts/:id/comments" => "comments#create", as: :create_comment
    delete "comments/:id" => "comments#destroy", as: :delete_comment

    get "/events" => "events#index", as: :event_map
    

  	
end

app/models/user.rb
class User < ActiveRecord::Base
    # geocoded_by :location
    # after_validation :geocode 
    mount_uploader :image, ImageUploader
    
    has_secure_password
    
      
    has_many :posts
    has_many :comments
    has_many :events

    validates :name, presence: true
   
    validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }

    validates :password, presence: true, length: { in: 6..20 }, confirmation: true

  attr_reader :password #add this line right below our list of fields


#we also need to create an @password instance variable and set it's value in our setter method
# def password=(unencrypted_password)
#   unless unencrypted_password.empty?
#     @password = unencrypted_password
#     self.password_digest = BCrypt::Password.create(unencrypted_password)
#   end
# end
def to_partial_path
    'posts/post'
end

end

app/controllers/users_controller.rb
  class UsersController < ApplicationController
  
    def index
        @users = User.all
    end
    
    def map 
        
        @users = User.all
        @user = User.new 
        @posts = Post.all.order('created_at DESC')
      #    if params[:query]
      #     search_field = params[:type].to_sym
      #     @posts = []
      #     @users.each do |user|
      #         if user[search_field].downcase.include? params[:query].downcase
      #             @posts << user.post
      #         end
      #       end
      #     # @posts = post.where(:name => params[:query])
      # else
      #   @posts = Post.all.order('created_at DESC')
      # end 
    end

    def new
        @user = User.new
    end
    
    def show
        @user = User.find(params[:id])
        @posts = @user.posts.order('created_at DESC')
        @comment = Comment.new
    end

    def create
        @user = User.new(user_params)

        if params[:image_id].present?
        preloaded = Cloudinary::PreloadedFile.new(params[:image_id])         
        raise "Invalid upload signature" if !preloaded.valid?
        @user.image_id = preloaded.identifier
        end

        respond_to do |format|
      if @user.save && @user.authenticate(user_params[:password])

        MyMailer.tester_email(@user).deliver_later
        
        session[:user_id] = @user.id
        flash["alert-success"] = "Hi #{current_user.name}! You are now logged in."
        format.html { redirect_to posts_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end

        # if User.create(user_params).valid?
        #     flash["alert-success"] = "You have been registered"
        #     redirect_to users_path
        # else
        #     flash["alert-warning"] = "Unable to register you"
        #     redirect_to new_user_path
        # end
    end

    def edit 
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])

        if params[:image_id].present?
        preloaded = Cloudinary::PreloadedFile.new(params[:image_id])         
        raise "Invalid upload signature" if !preloaded.valid?
        @user.image_id = preloaded.identifier
        end

      respond_to do |format|
        if @user.update(user_params) 
          format.html { redirect_to user_profile_path(@user), notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }

        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
        # if @user.update_attributes(params.require(:user).permit(:name, :email, :password, :password_confirmation, :image))
        #     redirect_to posts_path
        # else 
        #     render :show
    # end
    # end

    def destroy
        @user.destroy
        respond_to do |format|
        format.html { redirect_to users_path, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
        end
        # @user = User.find(params[:id])
        # @user.destroy
        # redirect_to users_path
    end

private

    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation, :age, :bio, :location, :image)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/home.html.erb
<div>
<image class="home_logo_photo" src="http://res.cloudinary.com/mckshreder/image/upload/c_fill,g_center,h_129,q_100,w_1065/v1441765874/Footy_main3_a8lsmq.png">
</div>

<div class="centered_container">


<div class="home_top_container">
	


			
			<!-- <div> -->
				<!-- <h4>WELCOME TO FOOTY</h4>
				<p>SKATE | FILM | SHARE</p> -->

			<!--<%= cl_image_tag("kfhtcyxxql9aquyeqn5j.png",class: "home_top_slider") %>-->
        	<!-- <h3 class="center"> THE FOOTY™ DASHBOARD</h3> -->

    	<!-- </div> -->

	<div class="home_top_object">
	<img class="home_top_photo" src="http://res.cloudinary.com/mckshreder/video/upload/c_fit,q_100,w_500/v1442030115/Garrettrefugioskate_fjme7s.gif">

		<div class="home_top_info">
		<h3>SKATE</h3>

		</div>
	</div>
	
	<div class="home_top_object">
	<img class="home_top_photo" src="http://res.cloudinary.com/mckshreder/video/upload/c_fill,g_center,h_500,w_500/v1441789298/ftrote5hahta3qyi2lq8.gif">

		<div class="home_top_info">
		<h3>FILM</h3>

		</div>
	</div>

	<div class="home_top_object">
	<img class="home_top_photo" src="http://res.cloudinary.com/mckshreder/video/upload/c_scale,h_500,w_500/v1442027508/lenny_mirror_slider_oirtqc.gif">

		<div class="home_top_info">
		<h3>SHARE</h3>

		</div>
	</div>

</div>

<div class="content">
	<!-- Start Demo -->

	<div class="cache">

		<!-- masks -->
		<img src="http://res.cloudinary.com/mckshreder/image/upload/v1442259122/footylogo_sliderbase_tv3ibx.svg">
		<img src="http://res.cloudinary.com/mckshreder/image/upload/v1442259122/footy_preslider_d6hkva.svg">
		<img src="http://res.cloudinary.com/mckshreder/image/upload/v1442259122/footylogo_sliderbackest_y7rxta.svg">
		<!-- photos -->
		<img src="http://res.cloudinary.com/mckshreder/image/upload/c_fill,h_960,w_1200/v1441947069/Pinnercrewmarvista_cysleq.jpg">
		<img src="http://res.cloudinary.com/mckshreder/image/upload/c_fill,h_960,w_1200/v1441947957/Issachandsgesture_i458la.jpg">
		<img src="http://res.cloudinary.com/mckshreder/image/upload/c_fill,h_960,w_1200/v1441947073/Curtmanny_hx6g9f.jpg">

	</div>

	<div class="wrapper feed_border">
		<div class="prism-slider">
			<ul class="navigation">
			</ul>
		</div>

		<div class="copy">
			<!-- <article> -->	
			<div class="feed_border">
				<h1>WELCOME TO FOOTY</h1>
				<p>SKATE | FILM | SHARE<p>
				<!-- <p>Film, edit, and share a fun video or a "Sponsor me clip" with your best footy.</p>
				<p>Upload your video to our skateboarding classfields. </p> -->
				<p>Instantly share your footy with companies, friends, and family all around the world... for FREE!</p>

				<!--<%= cl_image_tag("IMG_8589_co4izy.jpg", :crop => :fill, class: "homepage_photo_tag") %>-->
	        	<!-- <h5 class="center">YOUR FOOTY™ DASHBOARD</h5> -->
		        <%= link_to "POST FOOTY", new_post_path, class: "home_column_button"  %>
		        <%= link_to "CREATE EVENT", new_event_path, class: "home_column_button"  %>
		        <%= link_to "LOG IN", new_session_path, class: "home_column_button"  %>
		        <%= link_to "NEW ACCOUNT", new_user_path, class: "home_column_button"  %>
    		</div>
			
			
			<!-- </article> -->
		    
		</div>
	</div>


<div class="home_top_container">
		<div class="home_top_object">
	<img class="home_top_photo" src="http://res.cloudinary.com/mckshreder/image/upload/c_thumb,h_500,w_500/v1442023243/kevin_boardslide_fvbsnk.jpg">

		<div class="home_top_info">
		<ul class="text_list">
		
			<li>
				<p>#1. Have fun and skate with your friends everyday!</p>
			</li>
			<li>
				<p>#2. Film and edit a fun video or a "Sponsor me clip" with your best footy.</p>
			</li>
			<li>
				<p>#3. Upload your video to YouTube, copy the video url, and place ad with your video on our skateboarding classfields. </p>
			</li>
			<li>
				<p>#4. Instantly share your footy with companies, friends, and family all around the world... for FREE!</p>
			</li>
		</ul>

		</div>
	</div>
	<div class="home_top_object">
	<img class="home_top_photo" src="http://res.cloudinary.com/mckshreder/image/upload/c_thumb,g_north,h_500,w_500/v1442023060/Isaac_Wallride_dpbpw2.jpg">

		<div class="home_top_info">

		<ul class="text_list">
	      <li>
	        <p>#1. Scroll through classifieds and contact to the skater of your choice!</p>
	      </li>
	      <li>
	        <p>#2. Search skaters near you by your location on theFOOTYmap.</p>
	      </li>
	      <li>
	        <p>#3. Create a skate post for theFOOTY™app!</p>
	      </li>
	    </ul>

		</div>
	</div>
	<div class="home_top_object">
		<img class="home_top_photo" src="http://res.cloudinary.com/mckshreder/image/upload/c_thumb,h_500,q_100,w_500/v1441946922/Curtloks_LA-1_ua1fsx.jpg">
		
		<div class="home_top_info">
		<ul class="text_list">
      <li>
        <p>#1. Scroll through events and RSVP to the event of your choice!</p>
      </li>
      <li>
        <p>#2. Search events near you by your location on theFOOTYmap.</p>
      </li>
      <li>
        <p>#3. Create a skate event for theFOOTY™app!</p>
      </li>
    </ul>

		</div>
	</div>
</div>
	<!-- End Demo -->
</div>

		

app/views/users/index.html.erb
<h1 class="jumbotron"></h1>



<% flash.each do |key, value| %>
    <div class="alert <%= key %>"><%= value %></div>
<% end %>


<% if @users.count > 0 %>
    <% @users.each do |user| %>
        
    <div class = "video-info-container-header-top">    
            
    
    
           
              <%=image_tag user.image.url(:medium, class: "user-profile-photo_tag") %><%= "  " %><%= link_to user.name, user_profile_path(user) %>
              <h4 class="video-title-link">
              </h4> 
               
            
          
                <h4 class="video-email-link"><%= user.email %></h4> 
            
        
   
</div>
    <% end %>
<% else %>
    <h3>No Users Exist</h3>
    <hr>
<% end %>

app/views/users/map.html.erb
    

<script>
//= require jquery.turbolinks

var map;

function initialize() {
  var mapOptions = {
    zoom: 10,
    // mapTypeId: google.maps.MapTypeId.HYBRID
  };
  // google.maps,Map creates map on div canvas
  var map = new google.maps.Map(document.getElementById('map-canvas'),
      mapOptions);

  // this creates a location of the current users location 
	if(navigator.geolocation) {
	    navigator.geolocation.getCurrentPosition(function(position) {
	      	// this assigns the current users coordinats as pos
	      	var pos = new google.maps.LatLng(position.coords.latitude,
	                                       position.coords.longitude);
	      	// below creates the info window marker for current user location
	      	var infowindow = new google.maps.InfoWindow({
		        // must use map
		        map: map,
		        // assigns the window to show on map at current user location
		        position: pos,
		        content: 'your current location'
	      	});
	      	// brings the users map to center their location
	    	map.setCenter(pos);
	 	});

	 	handleNoGeolocation(true);
	}
	else {
    // Browser doesn't support Geolocation
    	handleNoGeolocation(false);
  	}
  	
  	// variable for all markers in post.all. We extract the data from the <select hidden, id = "marker_data" multiple> tag. data is ["123.1,-76.928"] Jquery
  	var markers = $("#marker_data").val();

	for (var i = 0; i < markers.length; i++) {
		// this splits data into two seperate strings of an array. Erase ","
		var coordinates = markers[i].split(",");
		// Number takes array turns strings into numbers for google pos variable
		var pos = new google.maps.LatLng(Number(coordinates[0]),Number(coordinates[1]));
	      console.log(pos);

	    
      	var contentString = '<h4>Info for this post coming soon...</h4>';

	  var infowindow = new google.maps.InfoWindow({
	      content: contentString
	  });
		
	    // this creates the marker in the user view
		var marker = new google.maps.Marker({
	      animation: google.maps.Animation.DROP,
	      position: pos,
	      map: map
	  
	  	});

		// this creates zoom when user clicks marker
        google.maps.event.addListener(marker, 'click', function() {
	     map.setZoom(10);
	     infowindow.open(map,marker);
	     map.setCenter(marker.getPosition());
	    });

	}
}

function handleNoGeolocation(errorFlag) {
  if (errorFlag) {
    var content = 'Error: The Geolocation service failed.';
  } else {
    var content = 'Error: Your browser doesn\'t support geolocation.';
  }
}

// jquery call to initalize () on load basically
$(document).ready(function() {
	initialize();
});
</script>

<!-- this contains the map on the view -->
<% flash.each do |key, value| %>
    <h4><%= value %></h4>
<% end %>



<div class="feed_container">
<!-- this contains the map on the view -->
<div class="left_column">

  <div class="feed_border">
      <h4 class="left">the FOOTY™app</h4>
      <h2 class="left">
      FOOTY CLASSIFIEDS.
        </h2>
      <!-- <hr class="small_line_break"> -->
    </div>
    
  <br>
  <%= form_tag('users#map', method: "get") do %>
    Search by
    <%= select_tag "type", options_for_select(["name", "location", "age"]) %> :
    <%= text_field_tag :query %>
    <%= submit_tag "Search", "class" => "btn-primary" %>
  <% end %>
  <h6>Search by "name", "age", or "location".</h6>
  <br>

  <% if @posts.count > 0 %>
    <% @posts.each do |post| %>
      
    <div class = "large_feed">

      <div class="video_top_info">
        <%= cl_image_tag(post.user.image,:width => 133, :height => 133, :crop => :fill, class: "user_profile_photo_tag") %>
        <%= "  " %>
        <%= post.user.name %>
        
        <div>
          <%= "| posted:" %>
          <span class="glyphicon glyphicon-time" aria-hidden="false">
          </span>
          <%= "  " + (remove_unwanted_words distance_of_time_in_words(Time.now, post.updated_at)) + " ago"  %>
        </div>
      </div> 
                       
    <div class="center">
      <%= cl_video_tag(post.video.to_s.split("/upload/").last.split(".").first, :video_codec=>"h264", :width=>493, :crop=>:scale, :controls => true, :poster => true, :fallback_content => "Your browser does not support HTML5 video tags")%>
    </div>
    
    <div class="video-poster, info-on-feed">
  
            <div class="video-poster">
          <div>
            <xsmall>Video title:</xsmall>
        <%= link_to "'#{post.title}'", post_path(id: post.id), :class => "title-link, blue" %>
          </div>
          </div>

      <hr class = "small_line_break">

          <xsmall>
            <%="Skater Info:"%>
          </xsmall> 
          
          <div class = "info-on-feed, center">
                  <p>Name: </p>
                  <p><%= link_to post.user.name ,  user_profile_path(post.user_id),:class => "option_link"%></p>
          </div>    
                  <p> Age: <%= post.user.age%></p>
                  <p> | City: <%= post.address%></p>
      <!-- <div class = "video-poster">
             <%= link_to post.user.name ,  user_profile_path(post.user_id), :class => "large_posts_title" %>
        </div> -->
    
      <div>
      <p>
        Options:
      </p>
            <%= link_to "#{post.user.name.split.first}'s "+"Profile",  user_profile_path(post.user_id), :class => "option_link" %>
            <%= "  &  "%>
            <%= link_to "Full Video", post_path(id: post.id), :class => "option_link" %>
          </div>
    </div> 


          <br>

        </div>
        
    <% end %>
    </div>
</div>  

<% else %>
    <h2>No Posts Exist</h2>
<% end %>
</div>
</div>



<!-- start of the right column -->
<div class="right_column">

<!-- this is the "sign in or sign up forum" -->
<% if current_user %>
    <ul id="topright_nav">
    <li>
     <%= cl_image_tag(current_user.image,:width => 133, :height => 133, :crop => :fill, class: "user_profile_photo_tag") %>
          <small>Hello, </small>
            
            <a><%= link_to "#{current_user.name}", user_profile_path(current_user) %>
            </a>
          <!-- <span class="glyphicon glyphicon-cog" aria-hidden="true">
          </span -->
          
          <ul> 
            <li>
                 <a><%= link_to "Your Profile", user_profile_path(current_user)%>
                 </a>
            </li> 
            <li>
                <a><%= link_to "Edit Account", edit_users_path(current_user) %>
                </a>
            </li>  
            <li>
                <a><%= link_to "Log out", destroy_session_path %>
                </a>
            </li>  
          </ul>
        </li>
    </ul>
    
    <div class="feed_border">
      <hr class = "small_line_break">
        <h5 class="center">YOUR FOOTY™ DASHBOARD</h5>
    <% if current_user %>
      <%= link_to "POST FOOTY", new_post_path, class: "right_column_button"  %>
      <%= link_to "CREATE EVENT", new_event_path, class: "right_column_button"  %>
      <%= link_to "EDIT ACCOUNT", edit_users_path(current_user), class: "right_column_button"  %>
      <%= link_to "LOG OUT", destroy_session_path, class: "right_column_button"  %>
    <% else %>
    <% end %>
    </div>

<% else %>

  <div class="feed_border">
        <h4 class="left">theFOOTY™app</h4>
        <h2 class="left">ALREADY A MEMBER?</h2>
    </div>
    
    <div class = "feed_border">
        <h5 class="center">SIGN IN TO YOUR FOOTY ACCOUNT</h5>
    <%= form_for @user, url: create_session_path do |f| %>

        <div class="form_group">
        <%= f.email_field :email, :placeholder => 'EMAIL', class: "form-control" %>
        </div>
    
        <div class="form_group"> 
        <%= f.password_field :password, :placeholder => 'PASSWORD', class: "form-control" %>
        </div>
    
        <%= f.submit "LOG IN", class: "submit-button-create, large_button" %>
    <% end %>
    <h5 class="center">NOT A MEMBER...?</h5>
    <%= link_to "CREATE YOUR ACCOUNT", new_event_path, class: "submit-button-create, large_button"  %>
    </div>

<% end %>


<!-- this is where the map begins -->
<div class="feed_border">
      <h3 class="center">
        GOT SKATE FOOTY?
      </h3>
      <h5 class="center">UPLOAD YOUR FOOTY FOR FREE</h5>
      <a class="submit-button-create, large_button" href="/posts/new">
       CREATE POST
      </a>

  <h4 class="left">theFOOTY™map</h4>
  <div id="map-canvas">
  </div>
  </div>
  <div class="feed_border">
    <!-- <h6 class="black" id = "event_logo">COMPANIES</h6> -->
    <h4><a  class="blue, right" href="">Search with Map here</a></h4>
  </div>

<h6 class="center">Local shredders near you</h6>

  <% @posts.each do |post| %>
    <div class="feed_border">

      <p>
        Title: 
        <%= link_to "#{post.title}" ,  user_profile_path(post.user_id)%>
      </p>
      <hr class = "line-break">
      
      <h6>
        Posted by: <%= link_to "#{post.user.name}" ,  user_profile_path(post.user_id), class: "blue" %>
      </h6>
      
      <h6>Age: 25<%= post.user.age%> | City:<%= post.address%></h6>     
      <p>
      <small>
          <span class="glyphicon glyphicon-time" aria-hidden="false">
          </span>
        <%= "  " + (remove_unwanted_words distance_of_time_in_words(Time.now, post.updated_at)) + " ago"  %>
      </small>
      </p>
      <h6 class="left">
            <%= link_to "Full Video", post_path(id: post.id), :class => "option_link" %>
      </h6>
    </div>
  <% end %>


  <div class="feed_border">
    <h4>VAN DOREN INVITATIONAL 2015</h4>
    <hr class = "line-break">
    <img alt="Icon" src="http://cdn.skateboarding.transworld.net/wp-content/blogs.dir/440/files/2015/08/Screen-Shot-2015-08-01-at-9.04.10-PM-600x383.png" />
    <!-- if you change these links look at .feed_border h4 and .feed_border p before. Just incase you dont need it -->
    <p class="black">Ben Hatchell is crowned champion for his second Van Doren Invitational title since winning the inaugural Van Doren Invitational in 2013.</p>
    <p><a  class="blue" href="http://www.vansusopenofsurfing.com/2015-skate">Full Details...</a></p>
  </div>



  <div class="feed_border">
  <h4>LANCE MOUNTAIN SIGNED FLIP BOARD GIVEAWAY</h4>
  <hr class = "line-break">
    <img alt="Icon" src="http://cdn.skateboarding.transworld.net/wp-content/blogs.dir/440/files/2015/07/TcoRy3lGp3E8_9OZTW53JzLaUN2rZw9Rr7msSiXxJ7qU75YPvgNwKr6fB2nWOmWBS2x9zeUdx6Gy1KLwHz5dKo0Dxvih-bmOaYEPNTYQoxYa6_Hcse-znq2wF2J5yWeLxV4h2nF8SY-i-XPf0GOcu3r45aytNHP4M4RYoKdCACTZAETxuGTrXf5b5okf2gjfbK16AwTFzOmZY6xMZdSqvbkAmWh-600x400.jpg" />
    <!-- if you change these links look at .feed_border h4 and .feed_border p before. Just incase you dont need it -->
    <p class="black">Want a signed Lance Mountain Flip board? Flip will be picking one winner each week for the next four weeks. Four winners total! Giveaway ends Friday, August 14, 2015</p>
    <!-- <br> -->
    <p><a  class="blue" href="https://www.facebook.com/nhsfunfactory?sk=app_190322544333196&ref=s">Click here to enter!</a></p>
  </div>
  <div class="feed_border">
  <!-- if you change these links look at .feed_border h4 and .feed_border p before. Just incase you dont need it -->
  <h4>"TRIALS AND TRIBULATIONS" VIDEO</h4>
  <hr class = "line-break">
  <img alt="Icon" src="http://cdn.skateboarding.transworld.net/wp-content/blogs.dir/440/files/2015/07/Screen-Shot-2015-07-28-at-4.41.23-PM-600x334.png" />
  <p class="black">Sure, the video part is the fine tuned, final presentation, but sometimes the raw, behind-the-scenes footy tells an even better story. Clive is a savage.</p>
  <p><a  class="blue" href="http://www.thrashermagazine.com/articles/videos/clive-dixons-trials-and-tribulations-video/">More details...</a></p>
  <!-- <br> -->
  </div>
 

  <div class="feed_border">
  <h4>Contact US</h4>
  <h4>THE FOOTY™ APP</h4>
  <p class="blue">garrettmckenzie@ymail.com</p>
  <hr class = "line-break">
  </div>



<!-- this creates ruby data in the view that can be accessed by JS if the <script> is on same exact file. multiple allows JS to know there is multple data  -->
<select hidden, id = "marker_data" multiple>
<% @posts.each do |post| %>
	<option selected = "true" value = "<%= post.latitude%>,<%= post.longitude%>, <%= post.title%>, <=% post.id %>">
	</option>	
<% end %>
</select>

app/views/users/new.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
            <li><%= message %>
            </li>
        <% end %>
      </ul>
    </div>
<% end %>


<div class="left_column">
  <div class="feed_border">
    <% flash.each do |key, value| %>
    <h4><%= value %></h4>
    <% end %>
      <h4 class="left">theFOOTY™app</h4>
      <h2 class = "left">SIGN UP FOR FREE!</h2>
    </div>
  
<div class="signup_form"> 
    <ul class="text_list">



<%= form_for @user, :html => { :multipart => true }, :method => :post do |f|  %>
   
    
    <div class="form_group">
    <h5 class="center">CREATE YOUR FOOTY ACCOUNT</h5>
    <%= f.text_field :name, :placeholder => 'NAME', class: "form-control"%>
    </div>
    
    <div class="form_group">
    <%= f.email_field :email, :placeholder => 'EMAIL', class: "form-control" %>
    </div>
    
    <div class="form_group"> 
    <%= f.password_field :password, :placeholder => 'PASSWORD', class: "form-control" %>
    </div>
    <div class="form_group">
    <%= f.password_field :password_confirmation, :placeholder => 'CONFIRM NEW PASSWORD', class: "form-control" %>
    </div>

    <div class="form_group">
    <%= f.text_field :age, :placeholder => 'YOUR AGE', class: "form-control"%>
    </div>

    <div class="form_group">
    <%= f.text_field :location, :placeholder => 'YOUR CITY AND STATE', class: "form-control" %>
    </div>

    <div class="form_group">
    <%= f.text_area :bio, :placeholder => 'YOUR BIO', class: "form-control"%>
    </div>

    <div class="form-group">
    <%= f.hidden_field(:image_cache)%>
    <%= f.file_field(:image, class: "form-control", :html => { :multiple => true }, id: "exampleInputFile")%>
    <p class="left">Upload Your Profile Photo<small>(Recommended.)</p>
    </div>

    <div class="actions">
    <%= f.submit "CREATE ACCOUNT", class: "submit-button-create, large_button"%>
    </div>
<% end %>
</div>

</ul>
  </div>
</div>


   
    

<!-- this is the user profile photo container  for right column-->
        

<!-- this is the "sign in or sign up forum" -->
<% if current_user %>
    <div class="right_column">

        <ul id="topright_nav">

        <li>
            <%= cl_image_tag(current_user.image,:width => 133, :height => 133, :crop => :fill, class: "user_profile_photo_tag") %>
                <small>Hello, </small>
                  
                  <a><%= link_to "#{current_user.name}", user_profile_path(current_user) %>
                  </a>
                 <!--  <span class="glyphicon glyphicon-cog" aria-hidden="true">
                  </span>
 -->              
              <ul> 
                <li>
                     <a><%= link_to "Your Profile", user_profile_path(current_user)%>
                     </a>
                </li> 
                <li>
                    <a><%= link_to "Edit Account", edit_users_path(current_user) %>
                    </a>
                </li>  
                <li>
                    <a><%= link_to "Log out", destroy_session_path %>
                    </a>
                </li>  
              </ul>
            </li>
        </ul>
        


    <div class="feed_border">
      <hr class = "small_line_break">
        <h5 class="center">YOUR FOOTY™ DASHBOARD</h5>
      </div>
    </div>






<% else %>

<div class="right_column">
    <div class="feed_border">
        <h4 class="left">theFOOTY™app</h4>
        <h2 class="left">ALREADY A MEMBER?</h2>
    </div>
    <div class = "feed_border">
        <h5 class="center">SIGN IN TO YOUR FOOTY ACCOUNT</h5>
        <%= form_for @user, url: create_session_path do |f| %>

        <div class="form_group">
        <%= f.email_field :email, :placeholder => 'EMAIL', class: "form-control" %>
        </div>
    
        <div class="form_group"> 
        <%= f.password_field :password, :placeholder => 'PASSWORD', class: "form-control" %>
        </div>
    
        <%= f.submit "Log in", class: "submit-button-create, large_button" %>
    <% end %>
    </div>
    <h4 class="center">theFOOTY™app</h4>
</div>
    <% end %>