config/routes.rb
Rails.application.routes.draw do
    
    resources :events

    root "users#home"
    get "/users" => "users#index", as: :users
    post "/users" => "users#create", as: :create_user
    get "/users/new" => "users#new", as: :new_user
    get "/users/map" => "users#map", as: :user_map
    get "/users/about" => "users#about", as: :about_footy
    get "/users/home" => "users#home"
    get "/users/welcome" => "users#welcome"
    get "/users/:id" => "users#show", as: :user_profile
    get "/users/:id/edit" => "users#edit", as: :edit_users
    put "/users/:id" => "posts#update", as: :update_user
    patch "/users/:id" =>"users#update"
    delete "/users/:id" => "users#destroy"


    get "/sessions/new" => "sessions#new", as: :new_session
    post "/sessions" => "sessions#create", as: :create_session
    get "/sessions/destroy" => "sessions#destroy", as: :destroy_session

    get "/posts" => "posts#index", as: :posts
    get "/posts/new" => "posts#new", as: :new_post
    post "/posts" => "posts#create", as: :create_post
    get "/posts/:id" => "posts#show", as: :post
    get "/posts/:id/edit" => "posts#edit", as: :edit_post
    put "/posts/:id" => "posts#update"
    patch "/posts/:id" => "posts#update"
    delete "posts/:id" => "posts#destroy"

    post "/posts/:id/comments" => "comments#create", as: :create_comment
    delete "comments/:id" => "comments#destroy", as: :delete_comment

    get "/events" => "events#index", as: :event_map
    

  	
end

app/models/post.rb
class Post < ActiveRecord::Base
  # attr_accessor :user_id, :name, :image, :remote_image_url, :video, :remote_video_url, :user
  belongs_to :user
  has_many :comments
  validates :title, presence: true
  validates :body, presence: true
  mount_uploader :image, ImageUploader
  mount_uploader :video, VideoUploader
  validate :file_size
  
  def file_size
    if video.file.size.to_f/(1000*1000) > 41943040
      errors.add(:file, "You cannot upload a file greater than 40MB")
      format.html { render :new }
      format.json { render json: @event.errors, status: :unprocessable_entity }
    end
  end

 geocoded_by :address   # can also be an IP address
	after_validation :geocode 
	
  



end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
 	 # before_action :authorize
 	def index
        @posts = Post.all.order('created_at DESC')
        @user = User.new
        
    end

    def new
    	@post = Post.new
        @event = Event.new
    end

    def show
        @posts = Post.all.shuffle
        @post = Post.find(params[:id])
        @comment = Comment.new
        @user = Post.find(params[:id])
    end

   def create
        @post = Post.new(post_params)
        # @events = Event.new(event_params)
        if params[:image_id].present?
          preloaded = Cloudinary::PreloadedFile.new(params[:image_id])         
          raise "Invalid upload signature" if !preloaded.valid?
          @event.image_id = preloaded.identifier
        end

        if params[:video_id].present?
          preloaded = Cloudinary::PreloadedFile.new(params[:video_id])         
          raise "Invalid upload signature" if !preloaded.valid?
          @event.video_id = preloaded.identifier
        end
        respond_to do |format|
            
        if current_user.posts.push @post
            
            format.html { redirect_to posts_path, notice: 'Post was successfully created.' }
            format.json { render :show, status: :created, location: @post }

      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
end

            

def edit
    @post = Post.find(params[:id])
end

def update
    @post = Post.find(params[:id])
    if @post.update_attributes(params.require(:post).permit(:title,:body,:youtube_url,:image, :address, :video))
        redirect_to posts_path
    else 
        render :edit
    end
end

def destroy
    @post = Post.find(params[:id])
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_path, notice: 'post was successfully destroyed.' }
      format.json { head :no_content }
    end
    
end


private
	def post_params
		params.require(:post).permit(:title,:body,:youtube_url, :image, :address, :video)
	end

    

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<script>
//= require jquery.turbolinks

var map;

function initialize() {
  var mapOptions = {
    zoom: 10,
    // mapTypeId: google.maps.MapTypeId.HYBRID
  };
  // google.maps,Map creates map on div canvas
  var map = new google.maps.Map(document.getElementById('map-canvas'),
      mapOptions);

  // this creates a location of the current users location 
	if(navigator.geolocation) {
	    navigator.geolocation.getCurrentPosition(function(position) {
	      	// this assigns the current users coordinats as pos
	      	var pos = new google.maps.LatLng(position.coords.latitude,
	                                       position.coords.longitude);
	      	// below creates the info window marker for current user location
	      	var infowindow = new google.maps.InfoWindow({
		        // must use map
		        map: map,
		        // assigns the window to show on map at current user location
		        position: pos,
		        content: 'your current location'
	      	});
	      	// brings the users map to center their location
	    	map.setCenter(pos);
	 	});

	 	handleNoGeolocation(true);
	}
	else {
    // Browser doesn't support Geolocation
    	handleNoGeolocation(false);
  	}
  	
  	// variable for all markers in post.all. We extract the data from the <select hidden, id = "marker_data" multiple> tag. data is ["123.1,-76.928"] Jquery
  	var markers = $("#marker_data").val();

	for (var i = 0; i < markers.length; i++) {
		// this splits data into two seperate strings of an array. Erase ","
		var coordinates = markers[i].split(",");
		// Number takes array turns strings into numbers for google pos variable
		var pos = new google.maps.LatLng(Number(coordinates[0]),Number(coordinates[1]));
	      console.log(pos);

	    
      	var contentString = '<h4>Info for this post coming soon...</h4>';

	  var infowindow = new google.maps.InfoWindow({
	      content: contentString
	  });
		
	    // this creates the marker in the user view
		var marker = new google.maps.Marker({
	      animation: google.maps.Animation.DROP,
	      position: pos,
	      map: map
	  
	  	});

		// this creates zoom when user clicks marker
        google.maps.event.addListener(marker, 'click', function() {
	     map.setZoom(10);
	     infowindow.open(map,marker);
	     map.setCenter(marker.getPosition());
	    });

	}
}

function handleNoGeolocation(errorFlag) {
  if (errorFlag) {
    var content = 'Error: The Geolocation service failed.';
  } else {
    var content = 'Error: Your browser doesn\'t support geolocation.';
  }
}

// jquery call to initalize () on load basically
$(document).ready(function() {
	initialize();
});
</script>
<% flash.each do |key, value| %>
    <h4><%= value %></h4>
<% end %>

<div class="feed_container">
<div class="left_column">
	<div class="feed_border">
      <h4 class="left">the FOOTY™app</h4>
      <h2 class="left">
      TODAY'S FEATURED SKATERS.
        </h2>
    </div>
	
	<% if @posts.count > 0 %>
    <% @posts.each do |post| %>
      
    <div class = "large_feed">

            <div class="video_top_info">
            <%= cl_image_tag(post.user.image,:width => 133, :height => 133, :crop => :fill, class: "user_profile_photo_tag") %>
            <%= "  " %><%= post.user.name %>

            <div>
            	<%= "| posted:" %>
	            <span class="glyphicon glyphicon-time" aria-hidden="false">
		        </span>
		        <%= "  " + (remove_unwanted_words distance_of_time_in_words(Time.now, post.updated_at)) + " ago"  %>
		    </div>
            </div> 

        <div class="center">
        	<%= cl_video_tag(post.video.to_s.split("/upload/").last.split(".").first, :video_codec=>"h264", :width=>493, :crop=>:scale, :controls => true, :poster => true, :fallback_content => "Your browser does not support HTML5 video tags")%>
      	</div>
		
		<div class="video-poster, info-on-feed">
	
          	<div class="video-poster">
	        <div>
          	<xsmall>Video title:</xsmall>
				<%= link_to "'#{post.title}'", post_path(id: post.id), :class => "title-link, blue" %>
	        </div>
	        </div>

			<hr class = "small_line_break">

	        <xsmall>
	        	<%="Skater Info:"%>
	        </xsmall> 
	        
	        <div class = "info-on-feed, center">
	                <p>Name: </p>
	                <p><%= link_to post.user.name ,  user_profile_path(post.user_id),:class => "option_link"%></p>
	        </div>  	
	                <p> Age: <%= post.user.age%></p>
	                <p> | City: <%= post.address%></p>
			<!-- <div class = "video-poster">
		         <%= link_to post.user.name ,  user_profile_path(post.user_id), :class => "large_posts_title" %>
		    </div> -->
		
			<div>
			<p>
				Options:
			</p>
	        	<%= link_to "#{post.user.name.split.first}'s "+"Profile",  user_profile_path(post.user_id), :class => "option_link" %>
	        	<%= "  &  "%>
	        	<%= link_to "Full Video", post_path(id: post.id), :class => "option_link" %>
	      	</div>
		</div> 

          <br>

        </div>
        
    <% end %>
    </div>
</div>  
  
<% else %>
    <h2>No Posts Exist</h2>
<% end %>

</div>

<!-- begining of the right side column on the home page -->
<div class="right_column">
<!-- this is the "sign in or sign up forum" -->
	<% if current_user %>
		<ul id="topright_nav">
		<li>
		    <%= cl_image_tag(current_user.image,:width => 133, :height => 133, :crop => :fill, class: "user_profile_photo_tag") %>
			    <small>Hello, </small>
			      
			      <a><%= link_to "#{current_user.name}", user_profile_path(current_user) %>
			      </a>
				 <!--  <span class="glyphicon glyphicon-cog" aria-hidden="true">
				  </span> -->
		      
		      <ul> 
		        <li>
		             <a><%= link_to "Your Profile", user_profile_path(current_user)%>
		             </a>
		        </li> 
		        <li>
		            <a><%= link_to "Edit Account", edit_users_path(current_user) %>
		            </a>
		        </li>  
		        <li>
		            <a><%= link_to "Log out", destroy_session_path %>
		            </a>
		        </li>  
		      </ul>
		    </li>
		</ul>
	<div class="feed_border">
      <hr class = "small_line_break">
        <h5 class="center">YOUR FOOTY™ DASHBOARD</h5>
    <% if current_user %>
      <%= link_to "POST FOOTY", new_post_path, class: "right_column_button"  %>
      <%= link_to "CREATE EVENT", new_event_path, class: "right_column_button"  %>
      <%= link_to "EDIT ACCOUNT", edit_users_path(current_user), class: "right_column_button"  %>
      <%= link_to "LOG OUT", destroy_session_path, class: "right_column_button"  %>
    <% else %>
    <% end %>
    </div>

	<% else %>
	
	<div class="feed_border">
        <h4 class="left">theFOOTY™app</h4>
        <h2 class="left">ALREADY A MEMBER?</h2>
    </div>
    
    <div class = "feed_border">
        <h5 class="center">SIGN IN TO YOUR FOOTY ACCOUNT</h5>
    <%= form_for @user, url: create_session_path do |f| %>

        <div class="form_group">
        <%= f.email_field :email, :placeholder => 'EMAIL', class: "form-control" %>
        </div>
    
        <div class="form_group"> 
        <%= f.password_field :password, :placeholder => 'PASSWORD', class: "form-control" %>
        </div>
    
        <%= f.submit "LOG IN", class: "submit-button-create, large_button" %>
    <% end %>
    <h5 class="center">NOT A MEMBER...?</h5>
    <%= link_to "CREATE YOUR ACCOUNT", new_event_path, class: "submit-button-create, large_button"  %>
    </div>

<% end %> 


		<div class="feed_border">
	    <h4 class="left">theFOOTY™map</h4>
		<div id="map-canvas">
		</div>
      

		  
		<div class="feed_border">
		<h4><a  class="blue, right" href="users/map">SEARCH BY MAP</a></h4>
		</div>


		<h2>Event News</h2>
		<h6>This weeks sponsored events</h6>
	</div>

	<div class="feed_border">
		<h4>VAN DOREN INVITATIONAL 2015</h4>
		<hr class = "line-break">
		<img alt="Icon" src="http://cdn.skateboarding.transworld.net/wp-content/blogs.dir/440/files/2015/08/Screen-Shot-2015-08-01-at-9.04.10-PM-600x383.png" />
		<!-- if you change these links look at .feed_border h4 and .feed_border p before. Just incase you dont need it -->
		<p class="black">Ben Hatchell is crowned champion for his second Van Doren Invitational title since winning the inaugural Van Doren Invitational in 2013.</p>
		<p><a  class="blue" href="http://www.vansusopenofsurfing.com/2015-skate">Full Details...</a></p>
	</div>



	<div class="feed_border">
	<h4>LANCE MOUNTAIN SIGNED FLIP BOARD GIVEAWAY</h4>
	<hr class = "line-break">
		<img alt="Icon" src="http://cdn.skateboarding.transworld.net/wp-content/blogs.dir/440/files/2015/07/TcoRy3lGp3E8_9OZTW53JzLaUN2rZw9Rr7msSiXxJ7qU75YPvgNwKr6fB2nWOmWBS2x9zeUdx6Gy1KLwHz5dKo0Dxvih-bmOaYEPNTYQoxYa6_Hcse-znq2wF2J5yWeLxV4h2nF8SY-i-XPf0GOcu3r45aytNHP4M4RYoKdCACTZAETxuGTrXf5b5okf2gjfbK16AwTFzOmZY6xMZdSqvbkAmWh-600x400.jpg" />
		<!-- if you change these links look at .feed_border h4 and .feed_border p before. Just incase you dont need it -->
		<p class="black">Want a signed Lance Mountain Flip board? Flip will be picking one winner each week for the next four weeks. Four winners total! Giveaway ends Friday, August 14, 2015</p>
		<!-- <br> -->
		<p><a  class="blue" href="https://www.facebook.com/nhsfunfactory?sk=app_190322544333196&ref=s">Click here to enter!</a></p>
	</div>
	<div class="feed_border">
	<!-- if you change these links look at .feed_border h4 and .feed_border p before. Just incase you dont need it -->
	<h4>"TRIALS AND TRIBULATIONS" VIDEO</h4>
	<hr class = "line-break">
	<img alt="Icon" src="http://cdn.skateboarding.transworld.net/wp-content/blogs.dir/440/files/2015/07/Screen-Shot-2015-07-28-at-4.41.23-PM-600x334.png" />
	<p class="black">Sure, the video part is the fine tuned, final presentation, but sometimes the raw, behind-the-scenes footy tells an even better story. Clive is a savage.</p>
	<p><a  class="blue" href="http://www.thrashermagazine.com/articles/videos/clive-dixons-trials-and-tribulations-video/">More details...</a></p>
	<!-- <br> -->
	</div>
	<div class="feed_border">
	<img alt="Icon" src="http://skateparkoftampa.com/spot/images3/damn-am-frontpage2.png" />
	<!-- if you change these links look at .feed_border h4 and .feed_border p before. Just incase you dont need it -->
	<h4>DAMN AM COSTA MESA, CA</h4>
	<p class="blue">August 7-9, 2015</p>
	<hr class = "line-break">
	<h4>DAMN AM WOODWARD, PA</h4>
	<p class="blue">August 27-29, 2015</p>
	</div>
	<div class="feed_border">
	<h4>SUBSCRIBE TO THRASHER</h4>
	<p><a  class="blue" href="http://shop.thrashermagazine.com/subscriptions/united-states.html">Click here to SUBSCRIBE!</a></p>
	<img alt="Icon" src="http://www.thrashermagazine.com/imagesV2/Junk_Drawer/2015/07/300aug15.jpg" />
	<hr class = "line-break">
	<p><a  class="blue" href="http://shop.thrashermagazine.com/subscriptions/united-states.html">Click here to SUBSCRIBE!</a></p>
	</div>

	<div class="feed_border">
	<h4>Contact US</h4>
	<h4>THE FOOTY™ APP</h4>
	<p class="blue">garrettmckenzie@ymail.com</p>
	<hr class = "line-break">
	</div>


<!-- this creates ruby data in the view that can be accessed by JS if the <script> is on same exact file. multiple allows JS to know there is multple data  -->
<select hidden, id = "marker_data" multiple>
<% @posts.each do |post| %>
	<option selected = "true" value = "<%= post.latitude%>,<%= post.longitude%>, <%= post.title%>, <=% post.id %>">
	</option>	
<% end %>
</select>

app/views/posts/new.html.erb
<div class="left_column">
  <div class="feed_border">
      <h4 class="left">the FOOTY™app</h4>
      <h2>POST YOUR FOOTY™</h2>
      <hr class="small_line_break">
      <h4 class="right">Please fill all fields below.</h4>
    </div>
  <div class="home_info"> 
    <ul class="text_list black">

<%= form_for @post, :html => { :multipart => true }, :method => :post do |f| %>
    
   <!-- <div class="form-group">
    <p>Upload a Photo<p>
    <%= f.hidden_field(:image_cache)%>
    <%= f.file_field(:image, :html => { :multiple => true })%>
    </div> -->

    <div class="form-group">
    <p>Upload a Video<p>
    <%= f.hidden_field(:video_cache)%>
    <%= f.file_field(:video, :chunk_size => 6_000_000, :html => { :multiple => true })%>
    </div>

    <div class="form-group">
    <%= f.label 'Title' %>
    <%= f.text_field :title, class: "form-control"%>
    </div>

    <div class="form-group">
    <%= f.label 'Caption' %>
    <%= f.text_area :body, class: "form-control"%>
    </div>


    <div class="form-group">
    <%= f.label 'Address (City, State)' %>
    <%= f.text_field :address, class: "form-control", placeholder: "eg.(Whittier, CA)" %>
    </div>


    <%= f.submit "Post", class: "submit-button-create" %>

<% end %>
    </ul>
  </div>
</div>


<!-- this is the user profile photo container  for right column-->
        

<!-- this is the "sign in or sign up forum" -->
<% if current_user %>
    <div class="right_column">

        <ul id="topright_nav">
        <li>
            <%= cl_image_tag(current_user.image,:width => 133, :height => 133, :crop => :fill, class: "user_profile_photo_tag") %>
                <small>Hello, </small>
                  
                  <a><%= link_to "#{current_user.name}", user_profile_path(current_user) %>
                  </a>
                 <!--  <span class="glyphicon glyphicon-cog" aria-hidden="true">
                  </span>
 -->              
              <ul> 
                <li>
                     <a><%= link_to "Your Profile", user_profile_path(current_user)%>
                     </a>
                </li> 
                <li>
                    <a><%= link_to "Edit Account", edit_users_path(current_user) %>
                    </a>
                </li>  
                <li>
                    <a><%= link_to "Log out", destroy_session_path %>
                    </a>
                </li>  
              </ul>
            </li>
        </ul>
        


    <div class="feed_border">
      <hr class = "small_line_break">
        <h5 class="center">YOUR FOOTY™ DASHBOARD</h5>
      </div>
    </div>






<% else %>

<div class="right_column">
    <div id="topright_nav">
        <!-- <h4 class="center">New to the Footy app?</h4>
        <h3 class="center">Sign up for Free!</h3>
        <p class="center">It's simple and easy.</p>
        <%= link_to "Create New Account", new_user_path, class: "submit-button, large_button" %>
        <hr> -->
        <h2 class="center">Hello, Sign in</h2>
        <h5 class="center">your footy™ account.</h5>

        <%= link_to "Log in", new_user_path, class: "submit-button, large_button" %>
    </div>
    <h4 class="center">theFOOTY™app</h4>
</div>
    <% end %>

    
<!-- <div class="right_column">
    <div class="home_info"> 
        <ul class="text_list">
            <h3>What to do...</h3>
            <li>
                <p>#1. Film and edit a fun video or a "Sponsor me clip" with your best footy.</p>
            </li>
            <li>
                <p>#2. Paste the YouTube url link into the form.</p>
            </li>
            <li>
                <p>#3. Complete all parts of the form.</p>
            </li>
            <li>
                <p>#4. Share your footy with the company of your choice!</p>
            </li>
        </ul>
    </div>
</div> -->

app/views/posts/show.html.erb
<div class="left_column">
<div class="video_top_info">
            <%= cl_image_tag(@post.user.image,:width => 133, :height => 133, :crop => :fill, class: "user_profile_photo_tag") %>
            <%= "  " %><%= @post.user.name %>

            <div>
                <%= "| posted:" %>
                <span class="glyphicon glyphicon-time" aria-hidden="false">
                </span>
                <%= "  " + (remove_unwanted_words distance_of_time_in_words(Time.now, @post.updated_at)) + " ago"  %>
            </div>
</div> 
 
    <div class="center">
        <%= cl_video_tag(@post.video.to_s.split("/upload/").last.split(".").first, :video_codec=>"h264", :width=>493, :crop=>:scale, :controls => true, :poster => true, :fallback_content => "Your browser does not support HTML5 video tags")%>
    </div>
    
    <div class ="video-info-container-header-top">
    <h5 class ="left"><small>Title: </small><%= @post.title %></h5>
    <h5 class ="left"><small>Video Info: </small><%= @post.body %></h5>
    <h5 class ="left"><small>Location: </small><%= @post.address %></h5>
    </div>

    <div class="feed_border">
        <h6>Contact info:</h6>
        <%= link_to "Direct message", user_profile_path(@post.user_id), class: "right_column_button" %>
        <%= link_to "#{@post.user.name.split.first}'s profile", user_profile_path(@post.user_id), class: "right_column_button" %> 
    </div>
    
</div>


<!-- this is the user profile photo container  for right column-->
        




<!-- this is the "sign in or sign up forum" -->
    <div class="right_column">
<% if current_user %>
        <ul id="topright_nav">
        <li>
          <%= cl_image_tag(current_user.image,:width => 133, :height => 133, :crop => :fill, class: "user_profile_photo_tag") %>
                <small>Hello, </small>
                  
                  <a><%= link_to "#{current_user.name}", user_profile_path(current_user) %>
                  </a>
                  <!-- <span class="glyphicon glyphicon-cog" aria-hidden="true">
                  </span> -->
              
              <ul> 
                <li>
                     <a><%= link_to "Your Profile", user_profile_path(current_user)%>
                     </a>
                </li> 
                <li>
                    <a><%= link_to "Edit Account", edit_users_path(current_user) %>
                    </a>
                </li>  
                <li>
                    <a><%= link_to "Log out", destroy_session_path %>
                    </a>
                </li>  
              </ul>
            </li>
        </ul>
      <hr class = "line_break">
      <div class="feed_border">
        <hr class = "small_line_break">
          <h5 class="center">YOUR FOOTY™ DASHBOARD</h5>
      <% if current_user %>
        <%= link_to "POST FOOTY", new_post_path, class: "right_column_button"  %>
        <%= link_to "CREATE EVENT", new_event_path, class: "right_column_button"  %>
        <%= link_to "EDIT ACCOUNT", edit_users_path(current_user), class: "right_column_button"  %>
        <%= link_to "LOG OUT", destroy_session_path, class: "right_column_button"  %>
      <% else %>
      <% end %>
      </div>

      <div class="rsvp_info">
        <h4 class="center">THIS SKATERS INFORMATION</h4>
        

      <ul class="text_list">

        <li>
          <p class="black"><small>Name:</small> 
            <%= @post.user.name%>        
          </p>
        </li>
        
        <li>
          <p class="black"><small>Age:</small> 
          <%= @post.user.age%> years old.
          </p>
        </li>

        <li>
          <p class="black"><small>Location :</small>
            <%= @post.user.location%>        </p>
        </li>
        
        <li>
          <p class="black"><small>Email: </small><%= @post.user.email%></p>
        </li>

        <li>
          <p class="black"><small>About Me:</small>
         <%= @post.user.bio%></p>
        </li>

      </ul>
    </div>

    
    <div class="feed_border">
        <h5>Contact info:</h5>
        <%= link_to "Direct message", user_profile_path(@post.user_id), class: "right_column_button" %>
        <%= link_to "#{@post.user.name.split.first}'s profile", user_profile_path(@post.user_id), class: "right_column_button" %> 
    </div>


    
        

    <%= link_to "Return to All Posts",  posts_path, :class => "title_link, blue" %>
    <%= link_to 'Destroy this post', @post, :class => "title_link_right", method: :delete, data: { confirm: 'Are you sure you want to delete this post?' } %>

</div>




<!-- ELSE!!!!! -->
<% else %>

<!-- <div class="right_column"> -->
<!-- <div class="right_column"> -->
    <div id="topright_nav">
        <!-- <h4 class="center">New to the Footy app?</h4>
        <h3 class="center">Sign up for Free!</h3>
        <p class="center">It's simple and easy.</p>
        <%= link_to "Create New Account", new_user_path, class: "submit-button, large_button" %>
        <hr> -->
        <h2 class="center">Hello, Sign in</h2>
        <h5 class="center">your footy™ account.</h5>

        <%= link_to "Log in", new_user_path, class: "submit-button, large_button" %>
    </div>
    <h4 class="center">the FOOTY™app</h4>
<!-- </div> -->
<div class="home_info">
        <h4 class="black">the FOOTY™ info</h4>
        <hr class = "line-break" >

      <ul class="text_list">
      
        <li>
          <p class="black"><small>Name:</small> 
            <%= @post.user.name%>        
          </p>
        </li>
        
        <li>
          <p class="black"><small>Age:</small> 
          <%= @post.user.age%> years old.
          </p>
        </li>

        <li>
          <p class="black"><small>Location :</small>
            <%= @post.user.location%>        </p>
        </li>
        
        <li>
          <p class="black"><small>Email: </small><%= @post.user.email%></p>
        </li>

        <li>
          <p class="black"><small>About Me:</small>
         <%= @post.user.bio%></p>
        </li>

      </ul>
    </div>

    <div class="feed_border">
    
     <hr class="small_line_break">
        <h4>Contact info:</h4>
        <%= link_to "Message #{@post.user.name.split.first}", user_profile_path(@post.user_id), class: "submit-button, large_button" %>


    </div>


</div>
    <% end %>