config/routes.rb
Rails.application.routes.draw do
    
    resources :events

    root "users#home"
    get "/users" => "users#index", as: :users
    post "/users" => "users#create", as: :create_user
    get "/users/new" => "users#new", as: :new_user
    get "/users/map" => "users#map", as: :user_map
    get "/users/about" => "users#about", as: :about_footy
    get "/users/home" => "users#home"
    get "/users/welcome" => "users#welcome"
    get "/users/:id" => "users#show", as: :user_profile
    get "/users/:id/edit" => "users#edit", as: :edit_users
    put "/users/:id" => "posts#update", as: :update_user
    patch "/users/:id" =>"users#update"
    delete "/users/:id" => "users#destroy"


    get "/sessions/new" => "sessions#new", as: :new_session
    post "/sessions" => "sessions#create", as: :create_session
    get "/sessions/destroy" => "sessions#destroy", as: :destroy_session

    get "/posts" => "posts#index", as: :posts
    get "/posts/new" => "posts#new", as: :new_post
    post "/posts" => "posts#create", as: :create_post
    get "/posts/:id" => "posts#show", as: :post
    get "/posts/:id/edit" => "posts#edit", as: :edit_post
    put "/posts/:id" => "posts#update"
    patch "/posts/:id" => "posts#update"
    delete "posts/:id" => "posts#destroy"

    post "/posts/:id/comments" => "comments#create", as: :create_comment
    delete "comments/:id" => "comments#destroy", as: :delete_comment

    get "/events" => "events#index", as: :event_map
    

  	
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FOOTY™</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= cloudinary_js_config %>
  
  <link href='https://fonts.googleapis.com/css?family=Michroma' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD9fLUHE8EU1Fyodf93hd4qPY1PsJ2rYIs"
  type="text/javascript"></script>
  <script src="http://widget.cloudinary.com/global/all.js" type="text/javascript">  
  </script>


  

</head>

<body class="container-fluid" >
<div>
  <%= image_tag ("FOOTY_logo_2.png"), :class => "footy_logo_img"%> 
</div>

<nav>
  
  <ul id = "my_new_nav">

    <li>
      <div class = "tab" id = "pink"><a class="nav_pad" href="/posts" data-no-turbolink>HOME</a></div>
        <div class = "dropdown_nav">
          <a class="nav_pad" id = "pink" href="/posts" data-no-turbolink>HOME</a>
      </div>
    </li> 
    
    <li>
       <div class = "tab" id = "orange"><a class="nav_pad" href="/users/map" data-no-turbolink>CLASSIFIEDS</a>
       </div>
        <div class = "dropdown_nav">
          <a class="nav_pad" id = "orange" href="/users/map" data-no-turbolink>CLASSIFIEDS</a>
        </div>
    </li>
    
    <li>
      <div class = "tab" id = "blue" href="#"><a class="nav_pad" href="/events" data-no-turbolink>EVENTS</a>
      </div>
      <div class = "dropdown_nav">
          <a class="nav_pad" id = "blue" href="/events" data-no-turbolink>EVENTS</a>
      </div> 
    </li>
    
<% if current_user %>
    <li>
       <div class = "tab" id = "purple" href="#">
         <%= link_to "YOUR ACCOUNT",  user_profile_path(current_user), class: "nav_pad", :id => "purple", 'data-no-turbolink' => true %>
            
       </div>



        <div class = "dropdown_nav">
          <%= link_to "YOUR PROFILE",  user_profile_path(current_user), class: "nav_pad", :id => "purple", 'data-no-turbolink' => true%>
          <%= link_to "EDIT PROFILE",  edit_users_path(current_user), class: "nav_pad", :id => "purple" %>
          <%= link_to "LOG OUT",  user_profile_path(current_user), class: "nav_pad", :id => "purple" %>
        </div>
    </li>
    

<% else %>
    
    <li>
       <div class = "tab" id = "purple" href="#">
       <%= link_to "NEW USER?", new_user_path, class: "nav_pad", :id => "purple" %>
       </div>
        <div class = "dropdown_nav">
        <%= link_to "START FOR FREE", new_user_path, class: "nav_pad", :id => "purple" %>

        </div>
    </li>
  <% end %>
    
    <li>
       <div class = "tab" id = "green" href="#">
        <%= link_to "ABOUT", about_footy_path, class: "nav_pad", :id => "green" %>
       </div>  
          <div class = "dropdown_nav">
            <%= link_to "ABOUT", about_footy_path, class: "nav_pad", :id => "green" %>
          </div>

    </li>

  </ul>
</nav>
<br class = "clear">


<%= yield %>

</body>
</html>